  spring:
    application:
      name: spring
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:63306/test?useTimezone=true&serverTimezone=UTC
      username: root
      password: 12345
    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: update
      show-sql: false